spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/Etica
    username: root
    password: root
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver

####api keys###

api_keys:
  tour_key: g9oAz%2BcyfYkUxh9M4DYk9Gr%2FLjOJHSdsSLJYOH%2BNwMsT4daTvMzQ2%2FPs%2BGs6R0bwuBQBwUJxsIzPUExpP9ddrw%3D%3D
  kakao_javascriptkey : 329f30d2ef6826903879d49a7d012a57

kakao:
  api:
    key: d478f40509760120a84b9bf99b52e7af
    secret: MPq91o7siRoGZctLLLIIIgLGsOuN3KEf
  redirect:
    uri: http://localhost:8080/user/oauth/callback

logout:
  redirect:
    uri: http://localhost:8080
